BaseUrl= "https://syui.cf/hugo-theme-air/"
LanguageCode= "en-US"
Title= "Cargo Start"
paginate = 5
DisqusShortname = ""
Copyright = "A.D. MMXX"
VatNumber = "2134234234234234"
canonifyurls = true

[author]
  name = "Cargo Start"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "start the change!"
  cover = "images/logo.jpg"
  author = "The Team"
  authorlocation = ""
  authorwebsite = ""
  bio= ""
  logo = "images/only_logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = ""
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]
