name = "Air"
license = "MIT"
licenselink = ""
description = "CargoStart Landing Page"
homepage = ""
tags = ["blog"]
features = ["disqus", "google analytics","share"]
min_version=0.14

[author]
  name = "syui"
  homepage = "https://syui.github.io"

[original]
  name = "hugo-theme-casper"
  homepage = "http://vjeantet.fr/"
  repo = "https://github.com/vjeantet/hugo-theme-casper"
